-- HTM Database Schema
-- Auto-generated from database using pg_dump
-- DO NOT EDIT THIS FILE MANUALLY
-- Run 'rake htm:db:schema:dump' to regenerate

--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;

--
-- Name: EXTENSION pg_trgm; Type: COMMENT; Schema: -; Owner: -
--

--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: -
--

--
-- Name: nodes_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.nodes_tags (
    id bigint NOT NULL,
    node_id bigint NOT NULL,
    tag_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

--
-- Name: TABLE nodes_tags; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.nodes_tags IS 'Join table connecting nodes to tags (many-to-many)';

--
-- Name: COLUMN nodes_tags.node_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes_tags.node_id IS 'ID of the node being tagged';

--
-- Name: COLUMN nodes_tags.tag_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes_tags.tag_id IS 'ID of the tag being applied';

--
-- Name: COLUMN nodes_tags.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes_tags.created_at IS 'When this association was created';

--
-- Name: node_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.node_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: node_tags_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.node_tags_id_seq OWNED BY public.nodes_tags.id;

--
-- Name: nodes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.nodes (
    id bigint NOT NULL,
    content text NOT NULL,
    speaker text NOT NULL,
    type text,
    category text,
    importance double precision DEFAULT 1.0,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    last_accessed timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    token_count integer,
    in_working_memory boolean DEFAULT false,
    robot_id bigint NOT NULL,
    embedding public.vector(2000),
    embedding_dimension integer,
    CONSTRAINT check_embedding_dimension CHECK (((embedding_dimension IS NULL) OR ((embedding_dimension > 0) AND (embedding_dimension <= 2000))))
);

--
-- Name: TABLE nodes; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.nodes IS 'Core memory storage for conversation messages and context';

--
-- Name: COLUMN nodes.content; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.content IS 'The conversation message/utterance content';

--
-- Name: COLUMN nodes.speaker; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.speaker IS 'Who said it: user or robot name';

--
-- Name: COLUMN nodes.type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.type IS 'Memory type: fact, context, code, preference, decision, question';

--
-- Name: COLUMN nodes.category; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.category IS 'Optional category for organizing memories';

--
-- Name: COLUMN nodes.importance; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.importance IS 'Importance score (0.0-1.0) for prioritizing recall';

--
-- Name: COLUMN nodes.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.created_at IS 'When this memory was created';

--
-- Name: COLUMN nodes.updated_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.updated_at IS 'When this memory was last modified';

--
-- Name: COLUMN nodes.last_accessed; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.last_accessed IS 'When this memory was last accessed';

--
-- Name: COLUMN nodes.token_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.token_count IS 'Number of tokens in the content (for context budget management)';

--
-- Name: COLUMN nodes.in_working_memory; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.in_working_memory IS 'Whether this memory is currently in working memory';

--
-- Name: COLUMN nodes.robot_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.robot_id IS 'ID of the robot that owns this memory';

--
-- Name: COLUMN nodes.embedding; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.embedding IS 'Vector embedding (max 2000 dimensions) for semantic search';

--
-- Name: COLUMN nodes.embedding_dimension; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.embedding_dimension IS 'Actual number of dimensions used in the embedding vector (max 2000)';

--
-- Name: nodes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.nodes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: nodes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.nodes_id_seq OWNED BY public.nodes.id;

--
-- Name: robots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.robots (
    id bigint NOT NULL,
    name text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    last_active timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    metadata jsonb
);

--
-- Name: TABLE robots; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.robots IS 'Registry of all LLM robots using the HTM system';

--
-- Name: COLUMN robots.name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.robots.name IS 'Human-readable name for the robot';

--
-- Name: COLUMN robots.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.robots.created_at IS 'When the robot was first registered';

--
-- Name: COLUMN robots.last_active; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.robots.last_active IS 'Last time the robot accessed the system';

--
-- Name: COLUMN robots.metadata; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.robots.metadata IS 'Robot-specific configuration and metadata';

--
-- Name: robots_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.robots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: robots_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.robots_id_seq OWNED BY public.robots.id;

--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version character varying NOT NULL
);

--
-- Name: tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tags (
    id bigint NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

--
-- Name: TABLE tags; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.tags IS 'Unique tag names for categorization';

--
-- Name: COLUMN tags.name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.tags.name IS 'Hierarchical tag in format: root:level1:level2 (e.g., database:postgresql:timescaledb)';

--
-- Name: COLUMN tags.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.tags.created_at IS 'When this tag was created';

--
-- Name: tags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: tags_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.tags_id_seq OWNED BY public.tags.id;

--
-- Name: nodes id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nodes ALTER COLUMN id SET DEFAULT nextval('public.nodes_id_seq'::regclass);

--
-- Name: nodes_tags id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nodes_tags ALTER COLUMN id SET DEFAULT nextval('public.node_tags_id_seq'::regclass);

--
-- Name: robots id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.robots ALTER COLUMN id SET DEFAULT nextval('public.robots_id_seq'::regclass);

--
-- Name: tags id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags ALTER COLUMN id SET DEFAULT nextval('public.tags_id_seq'::regclass);

--
-- Name: nodes_tags node_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nodes_tags
    ADD CONSTRAINT node_tags_pkey PRIMARY KEY (id);

--
-- Name: nodes nodes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nodes
    ADD CONSTRAINT nodes_pkey PRIMARY KEY (id);

--
-- Name: robots robots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.robots
    ADD CONSTRAINT robots_pkey PRIMARY KEY (id);

--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);

--
-- Name: tags tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_pkey PRIMARY KEY (id);

--
-- Name: idx_node_tags_node_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_node_tags_node_id ON public.nodes_tags USING btree (node_id);

--
-- Name: idx_node_tags_tag_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_node_tags_tag_id ON public.nodes_tags USING btree (tag_id);

--
-- Name: idx_node_tags_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_node_tags_unique ON public.nodes_tags USING btree (node_id, tag_id);

--
-- Name: idx_nodes_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_category ON public.nodes USING btree (category);

--
-- Name: idx_nodes_content_gin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_content_gin ON public.nodes USING gin (to_tsvector('english'::regconfig, content));

--
-- Name: idx_nodes_content_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_content_trgm ON public.nodes USING gin (content public.gin_trgm_ops);

--
-- Name: idx_nodes_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_created_at ON public.nodes USING btree (created_at);

--
-- Name: idx_nodes_embedding; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_embedding ON public.nodes USING hnsw (embedding public.vector_cosine_ops) WITH (m='16', ef_construction='64');

--
-- Name: idx_nodes_in_working_memory; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_in_working_memory ON public.nodes USING btree (in_working_memory);

--
-- Name: idx_nodes_last_accessed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_last_accessed ON public.nodes USING btree (last_accessed);

--
-- Name: idx_nodes_robot_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_robot_id ON public.nodes USING btree (robot_id);

--
-- Name: idx_nodes_speaker; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_speaker ON public.nodes USING btree (speaker);

--
-- Name: idx_nodes_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_type ON public.nodes USING btree (type);

--
-- Name: idx_nodes_updated_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_updated_at ON public.nodes USING btree (updated_at);

--
-- Name: idx_tags_name_pattern; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tags_name_pattern ON public.tags USING btree (name text_pattern_ops);

--
-- Name: idx_tags_name_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_tags_name_unique ON public.tags USING btree (name);

--
-- Name: nodes fk_rails_60162e9d3a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nodes
    ADD CONSTRAINT fk_rails_60162e9d3a FOREIGN KEY (robot_id) REFERENCES public.robots(id) ON DELETE CASCADE;

--
-- Name: nodes_tags fk_rails_b0b726ecf8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nodes_tags
    ADD CONSTRAINT fk_rails_b0b726ecf8 FOREIGN KEY (node_id) REFERENCES public.nodes(id) ON DELETE CASCADE;

--
-- Name: nodes_tags fk_rails_eccc99cec5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nodes_tags
    ADD CONSTRAINT fk_rails_eccc99cec5 FOREIGN KEY (tag_id) REFERENCES public.tags(id) ON DELETE CASCADE;

--
-- PostgreSQL database dump complete
--

\unrestrict aTUE7tRPerAY5DDFsbdi5fJ82pMSfgcpqwRIvAqzqGBgvhFeRL9YBW3YgvN05yl