-- HTM Database Schema
-- Auto-generated from database using pg_dump
-- DO NOT EDIT THIS FILE MANUALLY
-- Run 'rake htm:db:schema:dump' to regenerate

--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;

--
-- Name: EXTENSION pg_trgm; Type: COMMENT; Schema: -; Owner: -
--

--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: -
--

--
-- Name: nodes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.nodes (
    id bigint NOT NULL,
    content text NOT NULL,
    speaker text NOT NULL,
    type text,
    category text,
    importance double precision DEFAULT 1.0,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    last_accessed timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    token_count integer,
    in_working_memory boolean DEFAULT false,
    robot_id text NOT NULL,
    embedding public.vector(2000),
    embedding_dimension integer,
    CONSTRAINT check_embedding_dimension CHECK (((embedding_dimension IS NULL) OR ((embedding_dimension > 0) AND (embedding_dimension <= 2000))))
);

--
-- Name: TABLE nodes; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.nodes IS 'Core memory storage for conversation messages and context';

--
-- Name: COLUMN nodes.content; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.content IS 'The conversation message/utterance content';

--
-- Name: COLUMN nodes.speaker; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.speaker IS 'Who said it: user or robot name';

--
-- Name: COLUMN nodes.type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.type IS 'Memory type: fact, context, code, preference, decision, question';

--
-- Name: COLUMN nodes.category; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.category IS 'Optional category for organizing memories';

--
-- Name: COLUMN nodes.importance; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.importance IS 'Importance score (0.0-1.0) for prioritizing recall';

--
-- Name: COLUMN nodes.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.created_at IS 'When this memory was created';

--
-- Name: COLUMN nodes.updated_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.updated_at IS 'When this memory was last modified';

--
-- Name: COLUMN nodes.last_accessed; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.last_accessed IS 'When this memory was last accessed';

--
-- Name: COLUMN nodes.token_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.token_count IS 'Number of tokens in the content (for context budget management)';

--
-- Name: COLUMN nodes.in_working_memory; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.in_working_memory IS 'Whether this memory is currently in working memory';

--
-- Name: COLUMN nodes.robot_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.robot_id IS 'ID of the robot that owns this memory';

--
-- Name: COLUMN nodes.embedding; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.embedding IS 'Vector embedding (max 2000 dimensions) for semantic search';

--
-- Name: COLUMN nodes.embedding_dimension; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.embedding_dimension IS 'Actual number of dimensions used in the embedding vector (max 2000)';

--
-- Name: node_stats; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.node_stats AS
 SELECT type,
    count(*) AS count,
    avg(importance) AS avg_importance,
    sum(token_count) AS total_tokens,
    min(created_at) AS oldest,
    max(created_at) AS newest
   FROM public.nodes
  GROUP BY type;

--
-- Name: VIEW node_stats; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON VIEW public.node_stats IS 'Aggregated statistics by node type showing counts, importance, tokens, and age ranges.';

--
-- Name: nodes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.nodes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: nodes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.nodes_id_seq OWNED BY public.nodes.id;

--
-- Name: tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tags (
    id bigint NOT NULL,
    node_id bigint NOT NULL,
    tag text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

--
-- Name: TABLE tags; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.tags IS 'Hierarchical topic tags for flexible categorization using colon-delimited format';

--
-- Name: COLUMN tags.node_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.tags.node_id IS 'ID of the node being tagged';

--
-- Name: COLUMN tags.tag; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.tags.tag IS 'Hierarchical tag in format: root:level1:level2 (e.g., database:postgresql:timescaledb)';

--
-- Name: COLUMN tags.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.tags.created_at IS 'When this tag was created';

--
-- Name: ontology_structure; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.ontology_structure AS
 SELECT split_part(tag, ':'::text, 1) AS root_topic,
    split_part(tag, ':'::text, 2) AS level1_topic,
    split_part(tag, ':'::text, 3) AS level2_topic,
    tag AS full_path,
    count(DISTINCT node_id) AS node_count
   FROM public.tags
  WHERE (tag ~ '^[a-z0-9\-]+(:[a-z0-9\-]+)*$'::text)
  GROUP BY tag
  ORDER BY (split_part(tag, ':'::text, 1)), (split_part(tag, ':'::text, 2)), (split_part(tag, ':'::text, 3));

--
-- Name: VIEW ontology_structure; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON VIEW public.ontology_structure IS 'Provides a hierarchical view of all topics in the knowledge base. Topics use colon-delimited format (e.g., database:postgresql:timescaledb) and are assigned manually via tags.';

--
-- Name: operations_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.operations_log (
    id bigint NOT NULL,
    "timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    operation text NOT NULL,
    node_id bigint,
    robot_id text NOT NULL,
    details jsonb
);

--
-- Name: TABLE operations_log; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.operations_log IS 'Audit trail of all HTM operations for debugging and replay';

--
-- Name: COLUMN operations_log."timestamp"; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.operations_log."timestamp" IS 'When this operation occurred';

--
-- Name: COLUMN operations_log.operation; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.operations_log.operation IS 'Operation type: add, retrieve, remove, evict, recall';

--
-- Name: COLUMN operations_log.node_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.operations_log.node_id IS 'ID of the node affected by this operation (if applicable)';

--
-- Name: COLUMN operations_log.robot_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.operations_log.robot_id IS 'ID of the robot that performed this operation';

--
-- Name: COLUMN operations_log.details; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.operations_log.details IS 'Additional operation details and context';

--
-- Name: operations_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.operations_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: operations_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.operations_log_id_seq OWNED BY public.operations_log.id;

--
-- Name: relationships; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.relationships (
    id bigint NOT NULL,
    from_node_id bigint NOT NULL,
    to_node_id bigint NOT NULL,
    relationship_type text,
    strength double precision DEFAULT 1.0,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

--
-- Name: TABLE relationships; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.relationships IS 'Knowledge graph edges connecting related nodes';

--
-- Name: COLUMN relationships.from_node_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relationships.from_node_id IS 'Source node ID';

--
-- Name: COLUMN relationships.to_node_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relationships.to_node_id IS 'Target node ID';

--
-- Name: COLUMN relationships.relationship_type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relationships.relationship_type IS 'Type of relationship: relates_to, caused_by, follows, etc.';

--
-- Name: COLUMN relationships.strength; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relationships.strength IS 'Relationship strength/weight (0.0-1.0)';

--
-- Name: COLUMN relationships.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relationships.created_at IS 'When this relationship was created';

--
-- Name: relationships_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.relationships_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: relationships_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.relationships_id_seq OWNED BY public.relationships.id;

--
-- Name: robots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.robots (
    id text NOT NULL,
    name text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    last_active timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    metadata jsonb
);

--
-- Name: TABLE robots; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.robots IS 'Registry of all LLM robots using the HTM system';

--
-- Name: COLUMN robots.id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.robots.id IS 'Unique identifier for the robot';

--
-- Name: COLUMN robots.name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.robots.name IS 'Human-readable name for the robot';

--
-- Name: COLUMN robots.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.robots.created_at IS 'When the robot was first registered';

--
-- Name: COLUMN robots.last_active; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.robots.last_active IS 'Last time the robot accessed the system';

--
-- Name: COLUMN robots.metadata; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.robots.metadata IS 'Robot-specific configuration and metadata';

--
-- Name: robot_activity; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.robot_activity AS
 SELECT r.id,
    r.name,
    count(n.id) AS total_nodes,
    max(n.created_at) AS last_node_created
   FROM (public.robots r
     LEFT JOIN public.nodes n ON ((n.robot_id = r.id)))
  GROUP BY r.id, r.name;

--
-- Name: VIEW robot_activity; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON VIEW public.robot_activity IS 'Robot usage metrics showing total nodes created and last activity timestamp.';

--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version character varying NOT NULL
);

--
-- Name: tags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: tags_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.tags_id_seq OWNED BY public.tags.id;

--
-- Name: topic_relationships; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.topic_relationships AS
 SELECT t1.tag AS topic1,
    t2.tag AS topic2,
    count(DISTINCT t1.node_id) AS shared_nodes
   FROM (public.tags t1
     JOIN public.tags t2 ON (((t1.node_id = t2.node_id) AND (t1.tag < t2.tag))))
  GROUP BY t1.tag, t2.tag
 HAVING (count(DISTINCT t1.node_id) >= 2)
  ORDER BY (count(DISTINCT t1.node_id)) DESC;

--
-- Name: VIEW topic_relationships; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON VIEW public.topic_relationships IS 'Shows which topics co-occur on the same nodes, revealing cross-topic relationships in the knowledge base.';

--
-- Name: nodes id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nodes ALTER COLUMN id SET DEFAULT nextval('public.nodes_id_seq'::regclass);

--
-- Name: operations_log id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operations_log ALTER COLUMN id SET DEFAULT nextval('public.operations_log_id_seq'::regclass);

--
-- Name: relationships id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.relationships ALTER COLUMN id SET DEFAULT nextval('public.relationships_id_seq'::regclass);

--
-- Name: tags id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags ALTER COLUMN id SET DEFAULT nextval('public.tags_id_seq'::regclass);

--
-- Name: nodes nodes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nodes
    ADD CONSTRAINT nodes_pkey PRIMARY KEY (id);

--
-- Name: operations_log operations_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operations_log
    ADD CONSTRAINT operations_log_pkey PRIMARY KEY (id);

--
-- Name: relationships relationships_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.relationships
    ADD CONSTRAINT relationships_pkey PRIMARY KEY (id);

--
-- Name: robots robots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.robots
    ADD CONSTRAINT robots_pkey PRIMARY KEY (id);

--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);

--
-- Name: tags tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_pkey PRIMARY KEY (id);

--
-- Name: idx_nodes_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_category ON public.nodes USING btree (category);

--
-- Name: idx_nodes_content_gin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_content_gin ON public.nodes USING gin (to_tsvector('english'::regconfig, content));

--
-- Name: idx_nodes_content_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_content_trgm ON public.nodes USING gin (content public.gin_trgm_ops);

--
-- Name: idx_nodes_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_created_at ON public.nodes USING btree (created_at);

--
-- Name: idx_nodes_embedding; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_embedding ON public.nodes USING hnsw (embedding public.vector_cosine_ops) WITH (m='16', ef_construction='64');

--
-- Name: idx_nodes_in_working_memory; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_in_working_memory ON public.nodes USING btree (in_working_memory);

--
-- Name: idx_nodes_last_accessed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_last_accessed ON public.nodes USING btree (last_accessed);

--
-- Name: idx_nodes_robot_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_robot_id ON public.nodes USING btree (robot_id);

--
-- Name: idx_nodes_speaker; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_speaker ON public.nodes USING btree (speaker);

--
-- Name: idx_nodes_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_type ON public.nodes USING btree (type);

--
-- Name: idx_nodes_updated_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_updated_at ON public.nodes USING btree (updated_at);

--
-- Name: idx_operations_log_operation; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_operations_log_operation ON public.operations_log USING btree (operation);

--
-- Name: idx_operations_log_robot_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_operations_log_robot_id ON public.operations_log USING btree (robot_id);

--
-- Name: idx_operations_log_timestamp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_operations_log_timestamp ON public.operations_log USING btree ("timestamp");

--
-- Name: idx_relationships_from; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_relationships_from ON public.relationships USING btree (from_node_id);

--
-- Name: idx_relationships_to; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_relationships_to ON public.relationships USING btree (to_node_id);

--
-- Name: idx_relationships_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_relationships_unique ON public.relationships USING btree (from_node_id, to_node_id, relationship_type);

--
-- Name: idx_tags_node_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tags_node_id ON public.tags USING btree (node_id);

--
-- Name: idx_tags_tag; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tags_tag ON public.tags USING btree (tag);

--
-- Name: idx_tags_tag_pattern; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tags_tag_pattern ON public.tags USING btree (tag text_pattern_ops);

--
-- Name: idx_tags_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_tags_unique ON public.tags USING btree (node_id, tag);

--
-- Name: tags fk_rails_c2bba39827; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT fk_rails_c2bba39827 FOREIGN KEY (node_id) REFERENCES public.nodes(id) ON DELETE CASCADE;

--
-- PostgreSQL database dump complete
--

\unrestrict 2QwzilO33ZZqvHghcWKJCqTvuby7klgtmNFggsQmpeNDXGDQabWVffeH6aqG8fp