-- HTM Database Schema
-- Auto-generated from database using pg_dump
-- DO NOT EDIT THIS FILE MANUALLY
-- Run 'rake htm:db:schema:dump' to regenerate

--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;

--
-- Name: EXTENSION pg_trgm; Type: COMMENT; Schema: -; Owner: -
--

--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: -
--

--
-- Name: file_sources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.file_sources (
    id bigint NOT NULL,
    file_path text NOT NULL,
    file_hash character varying(64),
    mtime timestamp with time zone,
    file_size integer,
    frontmatter jsonb DEFAULT '{}'::jsonb,
    last_synced_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE ONLY public.file_sources ALTER COLUMN frontmatter SET COMPRESSION lz4;

--
-- Name: TABLE file_sources; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.file_sources IS 'Source file metadata for loaded documents';

--
-- Name: COLUMN file_sources.file_path; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.file_sources.file_path IS 'Absolute path to source file';

--
-- Name: COLUMN file_sources.file_hash; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.file_sources.file_hash IS 'SHA-256 hash of file content';

--
-- Name: COLUMN file_sources.mtime; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.file_sources.mtime IS 'File modification time';

--
-- Name: COLUMN file_sources.file_size; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.file_sources.file_size IS 'File size in bytes';

--
-- Name: COLUMN file_sources.frontmatter; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.file_sources.frontmatter IS 'Parsed YAML frontmatter';

--
-- Name: COLUMN file_sources.last_synced_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.file_sources.last_synced_at IS 'When file was last synced to HTM';

--
-- Name: file_sources_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.file_sources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: file_sources_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.file_sources_id_seq OWNED BY public.file_sources.id;

--
-- Name: node_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.node_tags (
    id bigint NOT NULL,
    node_id bigint NOT NULL,
    tag_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(6) without time zone
);

--
-- Name: TABLE node_tags; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.node_tags IS 'Join table connecting nodes to tags (many-to-many)';

--
-- Name: COLUMN node_tags.node_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.node_tags.node_id IS 'ID of the node being tagged';

--
-- Name: COLUMN node_tags.tag_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.node_tags.tag_id IS 'ID of the tag being applied';

--
-- Name: COLUMN node_tags.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.node_tags.created_at IS 'When this association was created';

--
-- Name: node_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.node_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: node_tags_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.node_tags_id_seq OWNED BY public.node_tags.id;

--
-- Name: nodes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.nodes (
    id bigint NOT NULL,
    content text NOT NULL,
    access_count integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    last_accessed timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    token_count integer,
    embedding public.vector(2000),
    embedding_dimension integer,
    content_hash character varying(64),
    deleted_at timestamp with time zone,
    source_id bigint,
    chunk_position integer,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT check_embedding_dimension CHECK (((embedding_dimension IS NULL) OR ((embedding_dimension > 0) AND (embedding_dimension <= 2000))))
);
ALTER TABLE ONLY public.nodes ALTER COLUMN content SET COMPRESSION lz4;
ALTER TABLE ONLY public.nodes ALTER COLUMN metadata SET COMPRESSION lz4;

--
-- Name: TABLE nodes; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.nodes IS 'Core memory storage for conversation messages and context';

--
-- Name: COLUMN nodes.content; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.content IS 'The conversation message/utterance content';

--
-- Name: COLUMN nodes.access_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.access_count IS 'Number of times this node has been accessed/retrieved';

--
-- Name: COLUMN nodes.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.created_at IS 'When this memory was created';

--
-- Name: COLUMN nodes.updated_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.updated_at IS 'When this memory was last modified';

--
-- Name: COLUMN nodes.last_accessed; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.last_accessed IS 'When this memory was last accessed';

--
-- Name: COLUMN nodes.token_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.token_count IS 'Number of tokens in the content (for context budget management)';

--
-- Name: COLUMN nodes.embedding; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.embedding IS 'Vector embedding (max 2000 dimensions) for semantic search';

--
-- Name: COLUMN nodes.embedding_dimension; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.embedding_dimension IS 'Actual number of dimensions used in the embedding vector (max 2000)';

--
-- Name: COLUMN nodes.content_hash; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.content_hash IS 'SHA-256 hash of content for deduplication';

--
-- Name: COLUMN nodes.deleted_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.deleted_at IS 'Soft delete timestamp - node is considered deleted when set';

--
-- Name: COLUMN nodes.source_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.source_id IS 'Reference to source file (for file-loaded nodes)';

--
-- Name: COLUMN nodes.chunk_position; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.chunk_position IS 'Position within source file (0-indexed)';

--
-- Name: COLUMN nodes.metadata; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.nodes.metadata IS 'Flexible metadata storage (memory_type, importance, source, etc.)';

--
-- Name: nodes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.nodes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: nodes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.nodes_id_seq OWNED BY public.nodes.id;

--
-- Name: robot_nodes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.robot_nodes (
    id bigint NOT NULL,
    robot_id bigint NOT NULL,
    node_id bigint NOT NULL,
    first_remembered_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    last_remembered_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    remember_count integer DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    working_memory boolean DEFAULT false NOT NULL,
    deleted_at timestamp(6) without time zone
);

--
-- Name: TABLE robot_nodes; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.robot_nodes IS 'Join table connecting robots to nodes (many-to-many)';

--
-- Name: COLUMN robot_nodes.robot_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.robot_nodes.robot_id IS 'ID of the robot that remembered this node';

--
-- Name: COLUMN robot_nodes.node_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.robot_nodes.node_id IS 'ID of the node being remembered';

--
-- Name: COLUMN robot_nodes.first_remembered_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.robot_nodes.first_remembered_at IS 'When this robot first remembered this content';

--
-- Name: COLUMN robot_nodes.last_remembered_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.robot_nodes.last_remembered_at IS 'When this robot last tried to remember this content';

--
-- Name: COLUMN robot_nodes.remember_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.robot_nodes.remember_count IS 'Number of times this robot has tried to remember this content';

--
-- Name: COLUMN robot_nodes.working_memory; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.robot_nodes.working_memory IS 'True if this node is currently in the robot working memory';

--
-- Name: robot_nodes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.robot_nodes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: robot_nodes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.robot_nodes_id_seq OWNED BY public.robot_nodes.id;

--
-- Name: robots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.robots (
    id bigint NOT NULL,
    name text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    last_active timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

--
-- Name: TABLE robots; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.robots IS 'Registry of all LLM robots using the HTM system';

--
-- Name: COLUMN robots.name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.robots.name IS 'Human-readable name for the robot';

--
-- Name: COLUMN robots.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.robots.created_at IS 'When the robot was first registered';

--
-- Name: COLUMN robots.last_active; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.robots.last_active IS 'Last time the robot accessed the system';

--
-- Name: robots_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.robots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: robots_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.robots_id_seq OWNED BY public.robots.id;

--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version character varying NOT NULL
);

--
-- Name: tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tags (
    id bigint NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(6) without time zone
);

--
-- Name: TABLE tags; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.tags IS 'Unique tag names for categorization';

--
-- Name: COLUMN tags.name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.tags.name IS 'Hierarchical tag in format: root:level1:level2 (e.g., database:postgresql:timescaledb)';

--
-- Name: COLUMN tags.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.tags.created_at IS 'When this tag was created';

--
-- Name: tags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: tags_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.tags_id_seq OWNED BY public.tags.id;

--
-- Name: file_sources id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.file_sources ALTER COLUMN id SET DEFAULT nextval('public.file_sources_id_seq'::regclass);

--
-- Name: node_tags id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.node_tags ALTER COLUMN id SET DEFAULT nextval('public.node_tags_id_seq'::regclass);

--
-- Name: nodes id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nodes ALTER COLUMN id SET DEFAULT nextval('public.nodes_id_seq'::regclass);

--
-- Name: robot_nodes id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.robot_nodes ALTER COLUMN id SET DEFAULT nextval('public.robot_nodes_id_seq'::regclass);

--
-- Name: robots id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.robots ALTER COLUMN id SET DEFAULT nextval('public.robots_id_seq'::regclass);

--
-- Name: tags id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags ALTER COLUMN id SET DEFAULT nextval('public.tags_id_seq'::regclass);

--
-- Name: file_sources file_sources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.file_sources
    ADD CONSTRAINT file_sources_pkey PRIMARY KEY (id);

--
-- Name: node_tags node_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.node_tags
    ADD CONSTRAINT node_tags_pkey PRIMARY KEY (id);

--
-- Name: nodes nodes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nodes
    ADD CONSTRAINT nodes_pkey PRIMARY KEY (id);

--
-- Name: robot_nodes robot_nodes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.robot_nodes
    ADD CONSTRAINT robot_nodes_pkey PRIMARY KEY (id);

--
-- Name: robots robots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.robots
    ADD CONSTRAINT robots_pkey PRIMARY KEY (id);

--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);

--
-- Name: tags tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_pkey PRIMARY KEY (id);

--
-- Name: idx_file_sources_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_file_sources_hash ON public.file_sources USING btree (file_hash);

--
-- Name: idx_file_sources_last_synced; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_file_sources_last_synced ON public.file_sources USING btree (last_synced_at);

--
-- Name: idx_file_sources_path_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_file_sources_path_unique ON public.file_sources USING btree (file_path);

--
-- Name: idx_node_tags_node_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_node_tags_node_id ON public.node_tags USING btree (node_id);

--
-- Name: idx_node_tags_tag_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_node_tags_tag_id ON public.node_tags USING btree (tag_id);

--
-- Name: idx_node_tags_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_node_tags_unique ON public.node_tags USING btree (node_id, tag_id);

--
-- Name: idx_nodes_access_count; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_access_count ON public.nodes USING btree (access_count);

--
-- Name: idx_nodes_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_active ON public.nodes USING btree (id) WHERE (deleted_at IS NULL);

--
-- Name: INDEX idx_nodes_active; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON INDEX public.idx_nodes_active IS 'Partial index for active (non-deleted) node queries';

--
-- Name: idx_nodes_active_with_embedding; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_active_with_embedding ON public.nodes USING btree (id) WHERE ((deleted_at IS NULL) AND (embedding IS NOT NULL));

--
-- Name: idx_nodes_content_gin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_content_gin ON public.nodes USING gin (to_tsvector('english'::regconfig, content));

--
-- Name: idx_nodes_content_hash_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_nodes_content_hash_unique ON public.nodes USING btree (content_hash);

--
-- Name: idx_nodes_content_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_content_trgm ON public.nodes USING gin (content public.gin_trgm_ops);

--
-- Name: idx_nodes_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_created_at ON public.nodes USING btree (created_at);

--
-- Name: idx_nodes_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_deleted_at ON public.nodes USING btree (deleted_at);

--
-- Name: idx_nodes_embedding; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_embedding ON public.nodes USING hnsw (embedding public.vector_cosine_ops) WITH (m='16', ef_construction='64');

--
-- Name: idx_nodes_last_accessed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_last_accessed ON public.nodes USING btree (last_accessed);

--
-- Name: idx_nodes_metadata; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_metadata ON public.nodes USING gin (metadata);

--
-- Name: idx_nodes_not_deleted_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_not_deleted_created_at ON public.nodes USING btree (created_at) WHERE (deleted_at IS NULL);

--
-- Name: idx_nodes_source_chunk_position; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_source_chunk_position ON public.nodes USING btree (source_id, chunk_position);

--
-- Name: idx_nodes_source_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_source_id ON public.nodes USING btree (source_id);

--
-- Name: idx_nodes_updated_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_updated_at ON public.nodes USING btree (updated_at);

--
-- Name: idx_robot_nodes_last_remembered_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_robot_nodes_last_remembered_at ON public.robot_nodes USING btree (last_remembered_at);

--
-- Name: idx_robot_nodes_node_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_robot_nodes_node_id ON public.robot_nodes USING btree (node_id);

--
-- Name: idx_robot_nodes_robot_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_robot_nodes_robot_id ON public.robot_nodes USING btree (robot_id);

--
-- Name: idx_robot_nodes_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_robot_nodes_unique ON public.robot_nodes USING btree (robot_id, node_id);

--
-- Name: idx_robot_nodes_working_memory; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_robot_nodes_working_memory ON public.robot_nodes USING btree (robot_id, working_memory) WHERE (working_memory = true);

--
-- Name: idx_tags_name_pattern; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tags_name_pattern ON public.tags USING btree (name text_pattern_ops);

--
-- Name: idx_tags_name_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tags_name_trgm ON public.tags USING gin (name public.gin_trgm_ops);

--
-- Name: idx_tags_name_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_tags_name_unique ON public.tags USING btree (name);

--
-- Name: index_node_tags_on_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_node_tags_on_deleted_at ON public.node_tags USING btree (deleted_at);

--
-- Name: index_robot_nodes_on_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_robot_nodes_on_deleted_at ON public.robot_nodes USING btree (deleted_at);

--
-- Name: index_tags_on_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_tags_on_deleted_at ON public.tags USING btree (deleted_at);

--
-- Name: nodes fk_rails_920ad16d08; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nodes
    ADD CONSTRAINT fk_rails_920ad16d08 FOREIGN KEY (source_id) REFERENCES public.file_sources(id) ON DELETE SET NULL;

--
-- Name: robot_nodes fk_rails_9b003078a8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.robot_nodes
    ADD CONSTRAINT fk_rails_9b003078a8 FOREIGN KEY (robot_id) REFERENCES public.robots(id) ON DELETE CASCADE;

--
-- Name: node_tags fk_rails_b51cdcc57f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.node_tags
    ADD CONSTRAINT fk_rails_b51cdcc57f FOREIGN KEY (tag_id) REFERENCES public.tags(id) ON DELETE CASCADE;

--
-- Name: node_tags fk_rails_ebc9aafd9f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.node_tags
    ADD CONSTRAINT fk_rails_ebc9aafd9f FOREIGN KEY (node_id) REFERENCES public.nodes(id) ON DELETE CASCADE;

--
-- Name: robot_nodes fk_rails_f2fc98d49e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.robot_nodes
    ADD CONSTRAINT fk_rails_f2fc98d49e FOREIGN KEY (node_id) REFERENCES public.nodes(id) ON DELETE CASCADE;

--
-- PostgreSQL database dump complete
--

\unrestrict bjkKIo8iBhvKUCAsIDDWdDnwALL0oxUsmZVbvgEad6ZmhcLmalGL4Ih7bfe9nlh